[supervisord]
nodaemon=true

[program:tigervnc]
# VNC desktop access
command=/usr/bin/Xtigervnc :1 -desktop "CS 265A" -depth 32 -geometry 1280x720 -localhost no -AcceptSetDesktopSize +extension RANDR -PasswordFile /home/ubuntu/.vnc/passwd
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
autorestart=true
priority=10
autorestart=true

[program:xfce4]
# starting an XFCE4 session with dbus-launch ensures XFCE can talk to
# its own components (panel, settings, etc.)
command=/usr/bin/dbus-launch --exit-with-session startxfce4
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu",DISPLAY=":1"
autorestart=true
# XFCE must start AFTER VNC has initialized the :1 display
priority=20

[program:websockify]
# Browser access via noVNC. Go to:
# http://127.0.0.1:6080/vnc.html?resize=remote
command=/usr/bin/websockify --web /usr/share/novnc/ 6080 localhost:5901
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
autorestart=true
priority=30
